### ISSUE TITLE
No performance gains with Tesseract `--user-words`

### ISSUE THREAD

**Issue by maehr** [maehr/ocr-dictionaries-for-federal-sources#5]
**Describe the bug**
Using tesseract 4.1 with `--user-words` does not improve OCR quality.

**Additional context**
`tesseract -v` outputs
```
tesseract 4.1.0
 leptonica-1.78.0
 libgif 5.1.4 : libjpeg 9c : libpng 1.6.37 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.3 : libopenjp2 2.3.1
 Found AVX2
 Found AVX
 Found SSE
```

**Possible solutions**
- https://github.com/tesseract-ocr/tesseract/blob/master/doc/tesseract.1.asc#config-files-and-augmenting-with-user-data
- https://medium.com/@vovaprivalov/tesseract-ocr-tips-custom-dictionary-to-improve-ocr-d2b9cd17850b**

**Comment by yumikim381** [comment]
Has this been fixed?

**Comment by maehr** [comment]
@yumikim381 please check upstream with tesseract. I do not maintain this repo anymore.
